# Generated by Django 4.0 on 2022-01-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('key_pair', models.CharField(default="b'-----BEGIN RSA PRIVATE KEY-----\\nMIICXAIBAAKBgQCLANjiYI6mCKbFkFr8QRJ5iM70CWk26jUIaR8X0DuPR11db+9+\\nh2pU36sAuStWhXHYE6SyktTFo4ICa0K0Eo+RsyVjaVPqy07EF4cAK99js+zPgKfi\\nAUPQYR/lCUCp75LIiD1jyf6/ccFmLFyzE8aqjcIAYjmgif67u2qBcM7SuwIDAQAB\\nAoGAAVKVK2yIDu+DkP+qMof21JvHD8DMUDNOkrqgwdLR0tQtt6u8jlgTN+4XLAOX\\nBrAnN5Rk1uxrlrZla9sK10rtWMStQmEWxOl9AVWBTcTX8hg9U910MRseq7acXiaz\\nocFpcaSYpmL5ecfK236aLQeCsEcMkudENBTZX16gXNNfnEECQQC6VVDezpAT/ZPy\\nwDzlQ0A+4w50BcDayEc3JaVDpCRjVUJDw1g+kQ0ZHd+4czlsZxj57eRspI0NgJZK\\n/Lxvf+4bAkEAvvllgLlvBR5ps+jmo5FBWbXnFaRN42wA+/bE7wwtJZUfYb1DWyim\\nn7F7phMIPUbn9PPbgv+OVT8gdFnRyBB34QJAL/P45f4+8gYWZyi2A0J1bDm+5Hj+\\nks9sFHMpvuilPLMaZJoHQcLOniIkCzIMGyvFL7zbRmJqsojfJNk6HW/M9QJAOYTu\\nUH4JdTY6ygg850kJsNZ72mXZW8Uc6sbhe8pkEqy+ffa+QceVoAWZ42RaF/KyTHHi\\nTKtiGETiJokjCSoEoQJBAJatXrvWdfpBfe0Kka1w/pzBsYUTRH2jWWIwyNw+pmtb\\nMXhTB4h99j3CEt0tQil5m0DLi52HhLpZhyBYfVd2m5o=\\n-----END RSA PRIVATE KEY-----'|b'-----BEGIN PUBLIC KEY-----\\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLANjiYI6mCKbFkFr8QRJ5iM70\\nCWk26jUIaR8X0DuPR11db+9+h2pU36sAuStWhXHYE6SyktTFo4ICa0K0Eo+RsyVj\\naVPqy07EF4cAK99js+zPgKfiAUPQYR/lCUCp75LIiD1jyf6/ccFmLFyzE8aqjcIA\\nYjmgif67u2qBcM7SuwIDAQAB\\n-----END PUBLIC KEY-----'", max_length=1024, unique=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
