# Generated by Django 4.0 on 2022-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_alter_accounts_balance_alter_accounts_key_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='key_pair',
        ),
        migrations.AddField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default='-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQDC2FtfSNBpOcW09e75EzkvUCt2FG0jbqOenOa90cG4GTlrf17d\nb11rxDK/GCQD+8hzRisjgCsQDCFzh1nIcGzvKC9O7POPVeNnxND9toKj2Ql0yTNz\nsJ/jjJeUfLeqE3vfh8TLgJc3R411MuhXHKlkqcd6DLinBjZuUodWsIjEVQIDAQAB\nAoGABB3VIIyeeyXrkmI/sVb3bZ8V654G6CxYzZF261pWZavCNoKLUwY0A44bRVz4\n9Izc6g1KNvyLtRenynPb0PNEB1auamdXa+jihte0fuMW7Wd3NJy2zE4nNHiJgmXE\nJOY1LrXGkr6I6Iui/NxhePDZ7w6NM9PZz47VhA3v/FrSkgECQQDYT/0G/4bH/ij7\n7EdrQHLURfXKcoL3oePpTm8jKB3U/qK0Be5kJgfCR3vMkkPhGN+GWrab4YpBmDvM\nhtvjXqoBAkEA5pgROCf7mxbIa9cNE0RrclC9vfZh3wXXg593s1vVE2Yt8nTKeeV4\nYkBwy5Kljfj9snspMhHvxFkWFIXfo6ZSVQJAQJmCwzhElC1/J90kZw9UO7i48sDI\nBBRA8EgQQLuWTSnOhVzQGPCSmJ6ohiuYQf0fpAwrRNpSY8yG70nHGVwIAQJBALbO\nKSB+uf16M0siwk/a9t86WSGmmHJI3FCRdECxdZsabyR+KCI4o5YohgMs76g8k0sS\nTldOVukuws1kUCYZbb0CQDlEEU2/EyycSyakMrrL8okJP9jj2Qr1CXUufBlStTGA\nenCH4SG8dSkNWutnQN+YYKBrv3TgfzOmhOxhrFUgMR8=\n-----END RSA PRIVATE KEY-----', max_length=1024, unique=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default='-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDC2FtfSNBpOcW09e75EzkvUCt2\nFG0jbqOenOa90cG4GTlrf17db11rxDK/GCQD+8hzRisjgCsQDCFzh1nIcGzvKC9O\n7POPVeNnxND9toKj2Ql0yTNzsJ/jjJeUfLeqE3vfh8TLgJc3R411MuhXHKlkqcd6\nDLinBjZuUodWsIjEVQIDAQAB\n-----END PUBLIC KEY-----', max_length=1024, unique=True),
        ),
    ]
