# Generated by Django 4.0 on 2022-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_remove_accounts_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='key_pair',
        ),
        migrations.AddField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default='-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCyMFg8DCviFP2VptT+ksR6SFrFrSYHnE9kGbpYHs7BbroENA1W\naKv+RaOSGvygAmCCBPszaIZUmkbeOiYi6qc8aTK6+tJRVzBWXZyoSCdWdoukw684\nyXkWjU6Nl5AoZsOvoSYgwWlxOSKdUdaUGq3PHWGhX+z5vw971v2q9FYd8QIDAQAB\nAoGAPoRiuLKmhNxLekF90lGJGMQhAOD2ik4Htr2mGPu6G7ivEAF5Ontf+MbTFFRe\nlP8wf/2ias997dnxClAJiE+e26e61C9q9v2LptuXO2NmL1k7R+riUOBhd8ilHnhy\nzVEA2SOlfWval9fD/HTs0TJqAaTIjublytr/2ZEKJb7kmBcCQQDP/w/y3a27NtNj\nF9hEUbTcMMsxVtFjBTSR3J7YHfL+5EEp9zd+Q3lZtn1MOs7zKNVLU6PdYsL0Kngu\nNDA0omTfAkEA21AuoJQiXW+NCmfJnJj5BlaKHt7sKRBXVDKNrGNR8A6Ryt946kH0\ntPGvxi1rFMSqNOV2Q+Zz855y7IsqzyyHLwJAQZQivCkmmItdtLWU611zj6UWu5Sq\n6fR/MaoErxEqRzFCVm/qoDW38hA2iy1TiJkMPva9CJUV8JPfVnn/5Oh6swJBAJQj\neRtmdEAA1ZgtuvVYLv2k/u8TTRn/u71X2HKVNAefD8OlZ5t0qcJ/bmfCzg3dOcs5\nI8WBqNjqMl6tMmF2hmkCQBuPcmZD5w4huT8L3/wdwpuvwBRKEA71HkXnyy8Vq7CV\nWE+AzGIDA/9F7DTBEszwGBaquhuurMVfuTuRIRBCVrw=\n-----END RSA PRIVATE KEY-----', max_length=1024),
        ),
        migrations.AddField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default='-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyMFg8DCviFP2VptT+ksR6SFrF\nrSYHnE9kGbpYHs7BbroENA1WaKv+RaOSGvygAmCCBPszaIZUmkbeOiYi6qc8aTK6\n+tJRVzBWXZyoSCdWdoukw684yXkWjU6Nl5AoZsOvoSYgwWlxOSKdUdaUGq3PHWGh\nX+z5vw971v2q9FYd8QIDAQAB\n-----END PUBLIC KEY-----', max_length=1024),
        ),
    ]
