# Generated by Django 4.0 on 2022-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0007_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default='-----BEGIN RSA PRIVATE KEY-----\nMIICWwIBAAKBgQDPGzyZ3rTZkhseX1HdeXZtgs1n31Q6YtJwLe6sWOm9vsBGWm5y\nE682x3oFqjaM3vcY6hfp4DHe/B5RlKGyYWpRkpfNLjVGaILvHBgwhA6yT4VNItkR\n0hcc+YMX4h+hQ/DVDtx8ITSzpv95RrSth/gZsf7SepcyvqsiKlVRG5EvAQIDAQAB\nAoGACbRuB4vPD67wBGFVFbq+WO1bMLXfXYkJ8WXFnF/iPBj3K5TLPh88A6YfSqqq\nObms/Ibjrfrqe1d3GD2Nwi0cbTaL6U4Ttz6LuFlm3+auhveDq1Gkgv+p6/5pm4tP\nKXZCstUzC0ZGvUzxxYtCMb92A0foTM7bHtEEbhp/xQSfSEECQQDmQiVTEBaagl/K\nwpKXfksjrbQMZjd1FkKygzS5W6ZLtjDf/TBn0qvXH/ZNufbNzdU5JBX0OCfGTh3Q\ncqoP/RFpAkEA5kJ+wqKzaLjg6t2iy8SIWGMS70iJJ9NzIe/4FvNueNdEk7+ppQq0\nOlGCDZdY+bSq2GukAQAfYcs1n4B+f9dl2QJAZvT8q39uG/hfzNHjqkmWX4W0FDdA\nZOJnQFraoGcSnJgCkqUrl8DjhXWNNIQKj0uSI9K23lSdtFYJjsM2t594wQJAIW8O\nUNynCFGv9upvtP64fX0FRtFVeP7u/MKHV23JYKqBPqLZ0ykWulETfT24oalmFT6r\n9ak65UxIYPybYZy5IQJAYqm4p2pFRz1GtiYavzaQZ9aH4Eiit77NIy2KqNdO9XFf\nJdFc8bAeE9LneFA5yGitEM6hbQo3+DYJ23ih1iCNJA==\n-----END RSA PRIVATE KEY-----', max_length=1024),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default='-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDPGzyZ3rTZkhseX1HdeXZtgs1n\n31Q6YtJwLe6sWOm9vsBGWm5yE682x3oFqjaM3vcY6hfp4DHe/B5RlKGyYWpRkpfN\nLjVGaILvHBgwhA6yT4VNItkR0hcc+YMX4h+hQ/DVDtx8ITSzpv95RrSth/gZsf7S\nepcyvqsiKlVRG5EvAQIDAQAB\n-----END PUBLIC KEY-----', max_length=1024),
        ),
    ]
