# Generated by Django 4.0 on 2022-01-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0008_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default='-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDWsiEMGxPvYn3HmOTp1Xg4dM+VBr1n64UzKvH7JqUXePTORuPM\nQqKt7UZEktklZjNEXACyDZ1Mtel4EE3QGGFYb2/Wtn3PZAbrPH0xLVkQag81Xozd\n5maQFnMY7wjrZZUZz9NlHTgO8ABQuYSCARgnB0VdJSmuMRF3Soj4LeWoYQIDAQAB\nAoGAZQ5zf78/Iu65RboyBd71N53EF+GURdYWXH9aZ11JWEMW+AFmOD8lU7jb2mtE\nytXQS90CdszxvaniuyDxf4H6T0lEwA87t+/tRbesVq+9fMXoSOnqGnEASgcVeJ+s\nKv1hmRQwwyKqvwiUgsxQuKfku0BkCxdO9J/63/NgOyv+6gECQQDhXNTaand/sj9/\ncW3A2pAEjpWlfUkK7Jje+xSZaXmT1NeOTXNv1Z88RfZVVVpcOsFFmsIck4flzfGG\n1fils/HbAkEA8+IRGKiHVJ6VH/M2caNPgVgiwjKZaZhH4sJgTvGuBbJDZyauEFLB\nEZL0rMkjdNHzyeeW0roqr0BWHGURfRb5cwJAb5UoKtDmRAq8l9xQrFlLT4ZNn/fN\nb6Q/+L+2rlLkCIctB19f1bKeuhgl5JBzQhExWsZKcB23/teeS9Wr3FehWwJBAO3B\nC82wLg5Ocy6smfz6qn18AJa1YV3R+PKVb/JGJdKj0JX03WhIZLPPQfxYMdqm+zVw\nMlbI6ufinpAb74q1JQUCQQDXWeKROC0qzrPBZmy17pSax9jc9OaXDotSkV+oJiho\nRbIO7fF3MLan2JC/ETvkKquaCcxd0h6yqI4ereNpccvH\n-----END RSA PRIVATE KEY-----', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default='-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDWsiEMGxPvYn3HmOTp1Xg4dM+V\nBr1n64UzKvH7JqUXePTORuPMQqKt7UZEktklZjNEXACyDZ1Mtel4EE3QGGFYb2/W\ntn3PZAbrPH0xLVkQag81Xozd5maQFnMY7wjrZZUZz9NlHTgO8ABQuYSCARgnB0Vd\nJSmuMRF3Soj4LeWoYQIDAQAB\n-----END PUBLIC KEY-----', max_length=1024, unique=True),
        ),
    ]
