# Generated by Django 4.0 on 2022-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0009_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default=b'-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCRFP3LhYQpYVWYoWi8pOmNUsISNP+CwMtk48wkW7eXwgvuG+Ee\nSvH1Xl6aKBwcvVvwVEX1HpB7LMyv1PBaSOg0HrpWsg3ie1x1s1n6CS2VTdl12VDX\nMJNVHuWcnCVPWZ++AHZFOCsbQxKGV+wqaq9AITt4PJ4CjYuoPdVU2lGNSwIDAQAB\nAoGAR8MC0Eb/+rne7Wq1VE4cCd/MB9Z4JhQ35vT4VmmZc7KzVPksTmASs2QU1hqN\n4TdWwRbmLZsLKyobKsPgiT/zvolfvaRmnfdHerUTlZmVHsw7eneXV9k9h1r/mj2q\nxYW2aYMfn4ppjIiVAC2edBfol4KNctFc+iAwOTjYeBr8Jy0CQQC9WJT4sM5Tn3bP\nzMxy+DiXCuUlQSg9mQdBQLt/GYtG8Hpdj9A/B/5zBKQynHH+PZKmZqdMUBwGFXbr\n1dfqawmVAkEAxCdwjClumE029GbeB2bCmudjeLYVBBiOwMawevSgJhCdhanmWWhM\n6uSEBpwl4ElsGP88sJNOJKowSQRxpPtDXwJBAK2b3OuxYVz3J38crpDz2x9SlAv2\nlCj2eNpxufituTBQKkJDLJO+hqV7Kfply3driV0dXmPwR+GkKKfQKOr9PYkCQCoG\nbSWKZuh4epKoS194k68ObhBZqm0DOepxZzQgnwMowib1/KUhJIGazfKAl9jSwjck\n0ALgvHg8gjXSnuqC7q8CQEBJVs/WW9yw/ybpCoNZtUUpu2IH4zE0sm1sqcW12sli\nNPoN2hmSog4FeVLr9HN9entAirS2NuwL9eV3y5gdSL0=\n-----END RSA PRIVATE KEY-----', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRFP3LhYQpYVWYoWi8pOmNUsIS\nNP+CwMtk48wkW7eXwgvuG+EeSvH1Xl6aKBwcvVvwVEX1HpB7LMyv1PBaSOg0HrpW\nsg3ie1x1s1n6CS2VTdl12VDXMJNVHuWcnCVPWZ++AHZFOCsbQxKGV+wqaq9AITt4\nPJ4CjYuoPdVU2lGNSwIDAQAB\n-----END PUBLIC KEY-----', max_length=1024, unique=True),
        ),
    ]
