# Generated by Django 4.0 on 2022-01-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0010_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default=b'-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCLo3+kz9Vw1qgWPlMCjq4zvMqEI0kgVGnYUGKNWoF2Q4LXdRaE\nL/EsgT5kUhWFqHkqb2+Z2Fd1CY+gbV6thZsPBHiffHn/mAAcD6CXEkCKW1xV59GV\n1FZMMO93kjvNcEMq3Zy+WJ+JHdqcp0eP43IBunNXi8e5BfVDCphjEbHQJwIDAQAB\nAoGAA3jRvCnUv0T/EeqDytz8VNn9WRK9hznCFfhNswEMlgGwt6W4JRpCD165S+pE\nkbmyJY12w2b/KbBOq2j8wSjAxbHoW+6D26niHoBCVnpeYj3TzgE+tBHH5xYkqasv\nHzMIEaI0Mqs4Tf8I9p6fIgwWYSvmryub0HYWI2o7yfkpYC0CQQC1mfAk9i2UM6/q\nmT79v9TITqLgoRvmj7Uuhg8Dj5b6PDnrk/cRyZUX4iHlSTu9wyQ9xLr1Wmbv+qIh\nhx4OSbs1AkEAxNiVSE8ViAkBBO0mKtVKyhxqM+5dasGBPk66+2vRk5lV64p8vnli\npjjyOLlVcqzcV90ufZtrZSS7ZwhIPd9tawJAAbT4tOA7fXEe7i2SkgADl/5lOYdK\nI9il81H/QiFPYfq+8J/rapdid18Awo71qMr0xD/dIgE/hnHspDQI7El1IQJBAIGS\nWzl8rRydaKlYfQ4m1hMR/ypt1doGw89CvbvvrcVtYmwn/ZLXjgMCaxbBkChq9qNz\neT2/B0NNmXnprrvjjT8CQC/4IK3BAAkZafAavmX18izsH5z7HFAvAoJ8xxuDy93a\n45l/DfvIUrz5tKapZZfuQkdpsCbLu5a81T1d/4yC7Hc=\n-----END RSA PRIVATE KEY-----', max_length=1024),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLo3+kz9Vw1qgWPlMCjq4zvMqE\nI0kgVGnYUGKNWoF2Q4LXdRaEL/EsgT5kUhWFqHkqb2+Z2Fd1CY+gbV6thZsPBHif\nfHn/mAAcD6CXEkCKW1xV59GV1FZMMO93kjvNcEMq3Zy+WJ+JHdqcp0eP43IBunNX\ni8e5BfVDCphjEbHQJwIDAQAB\n-----END PUBLIC KEY-----', max_length=1024),
        ),
    ]
