# Generated by Django 4.0 on 2022-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0011_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default=b'-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCcAvyHQ0X+Y4pcfoirTeaVS3ZZT5TILRpZzy/1LIkXgt1Iq1Lo\n3b6vtF2e1TiNFhfp+DnQCvUwVJ9Lm93IH7I5Lr0HUkGwbxTsFqIrjer0OJZis79c\nHIIYgZ9WLtShwUzZipcc6qDib0XHHsYR+eYlrf2E4Yz/7nvQAuoHabrNfwIDAQAB\nAoGAOktDYKdad/tpr7X4C0pIZnCUADskNMflmLk6Cjph308esBCUIj75CV4zvS2e\nu9kNhnch4wK1KyHzg6Tx8d0mEnJZsbY0YF+dLYfQqDKIvy+4mpo/GuVPLhHx5Hvl\nFKXfyY84hY46B7Dx5hpr/3pG8bSxQqv3x3HLnxO4GKiKRUECQQDAssHKHN0Ij4KR\n3zet3LNozy6OHcEuh2J8pIgM1xWh7a5mfgDbCgD3EAKnlH2VwYUg4SgUhJabpV6i\n8Q7ZtIllAkEAz0MEDGMlp0dNiHXX0yqWMiHrxlsMilnZjTfKOaRjnQaGD2tFThFB\n3fl6Z8iEWgo9viwXlPknkl3V0yS/r4X/EwJARgs0IdFoDsqLfZaT2KDWngxhMctj\nAxS3GfN8eJ5eAKQytpKqoPP78dJiBKQXGi5jw9XUCdFAJYdw5O2Wpk/XeQJBAJyj\nr1mVTQ3Ba61oMnbbRqwYytIcWbvt7+c0dNdfkBFKruLUVYqMrFUQiRwKhUxvVP52\n4FOsgeWymTl8GoqTIJUCQEMudelY6P51jkOv/1G0I+2AgA8i7zRESsjfoODsqe+3\n7r2suFg/x1/sBevKr7vPaCeH6TX1cYzWm73MuHE+1LU=\n-----END RSA PRIVATE KEY-----', max_length=1024),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD7/DEWIHCSYb7SH9LrnTgCkO7s\nWJIgUdf4UtZjFdOhIQRV9DDfO//da4zsgLqxDd9dPORc/a5ukDE/Dkb2oxeHIDmd\nfmuqEatsln4SGwTdzmrjI/kJrs1pWYAKp0RAMU2Ehai4pH8ouE824hNQKv9lvq7A\n9UolX+WrYOyB8/F0XwIDAQAB\n-----END PUBLIC KEY-----', max_length=1024),
        ),
    ]
