# Generated by Django 4.0 on 2022-01-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0013_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default=b'-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCJ4QZd3ipRqz4KeJ8nE6wXRIPkhUriLLzjVrYf7JBtoCrf2r+z\nRwPMBvw437sIpzZmRxveR8zcZ/rS4OSm6yIOxO1TN/34rHZQjhGFtYnUhWsHyEiK\ngbDhuQbT3LfeTn6obvT6gZbpkFjoGtSe4z3lUoYILsAHdRD8xNZ+TO3tBwIDAQAB\nAoGANPcP4ow/FnthTFV00eaRM6j6v5TipMrJzs0XDmFqQ+qEvdSC0qQjlcNTLafo\nadUOJTEIyBUt4bdB17NTsrldrd1lKEwekFVOA95BJoIu2imICj0pv5OhBGbUAOC2\nY4d987ZgEHrE7WicavewKfFzHLR4K66vxfoMOenzIOCFPIUCQQC5EA9sY0PslUbW\nRcpUcCLighMspIVnE1uuF+7D28viToPJLqhgS9hcMCLDdh528NQNyMoBp4Ppj2t6\n+ziGEy2dAkEAvrrkmAu3J961JJByPPZnwJxGu5SYx2jgEnbJRLwJ0jhbeTFSUeKJ\nf4KuVCENJoSyyTZPEqCWryE6/u8Jev7V8wJBAKUbZQdIkMM0c1ycK2WmHhmD/2Nm\n7PYHWVY7V/Q51u7zKbSGAgbX5BJrh7hnW8q2FhquNzu+nnv0TuoL1GQaHCkCQC6N\nd1YVJfM5TIVMLFXs3o4IlssaDeA+HNLk42M/cjY5Qzpla25JGL5iqyIlnwwTv3+V\nHd+yCpVcSwYGWg4HPTkCQGufSOuVI5pwe+SSEF1DyZV5Ekm3g4xYZdr93TiB6hz2\nvfcldNx3BZFXEQEEdEbcxSqcMycFYi9BpNkntDWVfrM=\n-----END RSA PRIVATE KEY-----', max_length=1024),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default=b'-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+4pwY8jQW+T64zEPRhksMdRe0\ncvXwme7QVnl+2SP8U6kPnqRrwlkWSL6dtMCtnH81VR/2XFhh9/ryqXI8T2eP75QK\nvciD4gHVl3QTLayT0dfzNDxa/bxE32kp/6MQ8VxxuFMAf54UJzgf4o14dABDZdak\n9NTvtf04RhwFCcoNEwIDAQAB\n-----END PUBLIC KEY-----', max_length=1024),
        ),
    ]
