# Generated by Django 4.0 on 2022-01-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0014_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='private_key',
            field=models.CharField(default='<function key_pair at 0x00000205A03A7130>', max_length=1024),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='public_key',
            field=models.CharField(default='<function key_pair at 0x00000205A03A7130>', max_length=1024),
        ),
    ]
