# Generated by Django 4.0 on 2022-01-24 05:55

from django.db import migrations, models
import wallet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0016_alter_accounts_private_key_alter_accounts_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='public_key',
        ),
        migrations.AddField(
            model_name='accounts',
            name='key_pair',
            field=models.CharField(default=wallet_app.models.key_pair, max_length=1024, unique=True),
        ),
    ]
