# Generated by Django 4.0 on 2022-01-24 06:40

from django.db import migrations, models
import wallet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0017_remove_accounts_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='key_pair',
            field=models.TextField(default=wallet_app.models.key_pair, max_length=1024, unique=True),
        ),
    ]
