# Generated by Django 4.0 on 2022-01-30 12:39

from django.db import migrations, models
import wallet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0018_alter_accounts_key_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='key_pair',
            field=models.CharField(default=wallet_app.models.key_pair, max_length=1024, unique=True),
        ),
    ]
