# Generated by Django 4.0 on 2022-02-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0022_alter_accounts_key_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_type',
            field=models.IntegerField(default=0),
        ),
    ]
